by/Lesson 08
Web-Laboratory-Ordynski/cobra-03 pull request #27
Opened 2020-07-01 14:20 UTC by lamoregrande

2020-07-01 15:02 UTC, MixalsWork approved these changes

2020-07-02 12:14 UTC, ostannja commented on homework/yulia-batkalova/lesson-08/WhoWeAre/WhoWeAre/index.html
> +        <div class="">
empty class name

2020-07-02 12:19 UTC, ostannja approved these changes
great job!

2020-07-02 12:19 UTC, ostannja commented on homework/yulia-batkalova/lesson-08/WhoWeAre/WhoWeAre/index.html
> +        <div class="">
empty class name

2020-07-02 12:19 UTC, ostannja commented on homework/yulia-batkalova/lesson-08/WhoWeAre/WhoWeAre/index.html
> +        <div class="">
empty class name

2020-07-02 12:19 UTC, ostannja commented on homework/yulia-batkalova/lesson-08/WhoWeAre/WhoWeAre/index.html
> +        <div class="">
empty class name

2020-07-03 08:20 UTC, lamoregrande commented on homework/yulia-batkalova/lesson-08/WhoWeAre/WhoWeAre/index.html
> +        <div class="">
> empty class name

Thanks

2020-07-03 13:18 UTC, AlexOrd requested changes

2020-07-03 13:18 UTC, AlexOrd commented on homework/yulia-batkalova/lesson-08/WhoWeAre/WhoWeAre/index.html
> +        <div class="">
has to fixed

2020-07-03 13:22 UTC, AlexOrd requested changes

2020-07-03 13:22 UTC, AlexOrd commented on homework/yulia-batkalova/index.html
> +    <!-- <a href="lesson-01/index.html"><h1>Lesson-01</h1></a>
Почему закомментировано?

2020-07-03 13:22 UTC, AlexOrd commented
Нужно добавить .DS_Store в гитигнор.

2020-07-03 15:32 UTC, AlexOrd approved these changes

2020-07-08 18:17 UTC, merged